version: "3.9"

services:
  web:
    build: backend
    ports:
      - "9000:9000"
    command: "poetry run python3 -m uvicorn web:app --host 0.0.0.0 --port 9000 --reload"
    volumes:
      - ./backend/:/app

volumes:
  backend: