version: "3.9"

services:
  web:
    build: .
    ports:
      - "9000:9000"
    command: "poetry run python3 -m uvicorn app.web:app --host 0.0.0.0 --port 9000"
    volumes:
      - .:/app

volumes:
  backend: